### ISSUE TITLE
1.7.10 Support

### ISSUE THREAD

**Issue by Quibilia** [AgeCraft/ExtendedMetadata#1]
Would it be possible for you to compile a version of ExtendedMetadata for Minecraft 1.7.10?

I am currently testing a modpack with about 340 mods. I've got everything set up, but since the block ID limit is 4096, I am obviously receiving an error when the highest block ID that is registered is 8466. There is no other mod like yours that I am aware of, and it would be fantastic if I could use it, since it is essentially a necessity if I am going to get my modpack working.

Quibilia

**Comment by DanielHuisman** [comment]
I can't "just compile a 1.7.10 version". Since this mod edits the Minecraft source code through ASM, I need to basically rewrite the whole mod as the 1.7.10 source code that deals with block IDs and metadata is completely different from 1.8. If I have time for it I might make a 1.7.10 version as multiple people have asked for it, but it will take a lot of work to make it.

**Comment by Quibilia** [comment]
I understand. Godspeed!

**Comment by DanielHuisman** [comment]
I will look at the 1.7.10 source code somewhere this week, based on that I will decide if I'm going to make a 1.7.10 version

**Comment by Quibilia** [comment]
If you'd like some help, I am a programmer. I'm not very experienced with Java, but I am very experienced with C# and C++, and I'm sure my skills will translate easily.

**Comment by DanielHuisman** [comment]
Not sure you can help, you need to be able to read and understand Java bytecode.
But I have finished my current work on the 1.8 branch, so I can focus on the 1.7 branch now.

**Comment by Adaptivity** [comment]
340 mods? You are crazy you know but you can use this https://github.com/fewizz/NotEnoughIDs/releases It wasn't tested a lot but should work with every mod.

**Comment by Quibilia** [comment]
Ha, thanks for the reference, I'll check it out. Since I last talked to you, I took another look through a mod listing for things I might have missed, and the number is now around 380.

I've been crazy for a long time.

**Comment by DanielHuisman** [comment]
I'm sorry but I'm not going to add 1.7 support as Forge 1.8.8 will be released soon and in the not too distant future Minecraft 1.9 aswell.
I will update to Forge 1.8.8 as fast as I can and I'd recommend updating any mods you have to 1.8 / 1.8.8.
