### ISSUE TITLE
Increase block ID limit from 2^15 to 2^16

### ISSUE THREAD

**Issue by hilburn** [AgeCraft/ExtendedMetadata#3]
From what I can tell from the CF post you use 32k block IDs rather than 65k because the int is unsigned, however you are performing bitwise operations on the integer to split it into the metadata and block ID anyway and with unsigned ints:

0xFFFFFFFF = -1

0xFFFFFFFF & 0xFFFF = 65k

0xFFFFFFFF >> 16 = 65k

**Comment by DanielHuisman** [comment]
I will change to a block ID limit of 2^16 once Mojang enforces Java 8 just to be safe. Because I'm still convinced Java 6 and Java 7 don't fully support unsigned integers.

**Comment by DanielHuisman** [comment]
I force Java 8 as a dependency, so soon I will update to 2^16 block ID support

**Comment by DanielHuisman** [comment]
This project is inactive, closing as wontfix.
